/*
* generated by Xtext
*/
package org.deg.xtext.gui.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class GuiDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class UIDescriptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UIDescription");
		private final UnorderedGroup cUnorderedGroup = (UnorderedGroup)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cUnorderedGroup.eContents().get(0);
		private final Assignment cAreaCountAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cAreaCountAreaCountParserRuleCall_0_0_0 = (RuleCall)cAreaCountAssignment_0_0.eContents().get(0);
		private final Assignment cTypeDefinitionAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cTypeDefinitionTypeDefinitionParserRuleCall_0_1_0 = (RuleCall)cTypeDefinitionAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cUnorderedGroup.eContents().get(1);
		private final Assignment cPropertyAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cPropertyPropertyParserRuleCall_1_0_0 = (RuleCall)cPropertyAssignment_1_0.eContents().get(0);
		private final Assignment cUsedDescriptionsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cUsedDescriptionsUsedDescriptionsParserRuleCall_1_1_0 = (RuleCall)cUsedDescriptionsAssignment_1_1.eContents().get(0);
		private final Assignment cDefinitionsAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cDefinitionsDefinitionParserRuleCall_1_2_0 = (RuleCall)cDefinitionsAssignment_1_2.eContents().get(0);
		private final Assignment cAreasAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cAreasAreaAssignmentParserRuleCall_1_3_0 = (RuleCall)cAreasAssignment_1_3.eContents().get(0);
		
		//UIDescription:
		//	areaCount=AreaCount typeDefinition=TypeDefinition & property=Property usedDescriptions+=UsedDescriptions*
		//	definitions+=Definition* areas+=AreaAssignment*;
		public ParserRule getRule() { return rule; }

		//areaCount=AreaCount typeDefinition=TypeDefinition & property=Property usedDescriptions+=UsedDescriptions*
		//definitions+=Definition* areas+=AreaAssignment*
		public UnorderedGroup getUnorderedGroup() { return cUnorderedGroup; }

		//areaCount=AreaCount typeDefinition=TypeDefinition
		public Group getGroup_0() { return cGroup_0; }

		//areaCount=AreaCount
		public Assignment getAreaCountAssignment_0_0() { return cAreaCountAssignment_0_0; }

		//AreaCount
		public RuleCall getAreaCountAreaCountParserRuleCall_0_0_0() { return cAreaCountAreaCountParserRuleCall_0_0_0; }

		//typeDefinition=TypeDefinition
		public Assignment getTypeDefinitionAssignment_0_1() { return cTypeDefinitionAssignment_0_1; }

		//TypeDefinition
		public RuleCall getTypeDefinitionTypeDefinitionParserRuleCall_0_1_0() { return cTypeDefinitionTypeDefinitionParserRuleCall_0_1_0; }

		//property=Property usedDescriptions+=UsedDescriptions* definitions+=Definition* areas+=AreaAssignment*
		public Group getGroup_1() { return cGroup_1; }

		//property=Property
		public Assignment getPropertyAssignment_1_0() { return cPropertyAssignment_1_0; }

		//Property
		public RuleCall getPropertyPropertyParserRuleCall_1_0_0() { return cPropertyPropertyParserRuleCall_1_0_0; }

		//usedDescriptions+=UsedDescriptions*
		public Assignment getUsedDescriptionsAssignment_1_1() { return cUsedDescriptionsAssignment_1_1; }

		//UsedDescriptions
		public RuleCall getUsedDescriptionsUsedDescriptionsParserRuleCall_1_1_0() { return cUsedDescriptionsUsedDescriptionsParserRuleCall_1_1_0; }

		//definitions+=Definition*
		public Assignment getDefinitionsAssignment_1_2() { return cDefinitionsAssignment_1_2; }

		//Definition
		public RuleCall getDefinitionsDefinitionParserRuleCall_1_2_0() { return cDefinitionsDefinitionParserRuleCall_1_2_0; }

		//areas+=AreaAssignment*
		public Assignment getAreasAssignment_1_3() { return cAreasAssignment_1_3; }

		//AreaAssignment
		public RuleCall getAreasAreaAssignmentParserRuleCall_1_3_0() { return cAreasAreaAssignmentParserRuleCall_1_3_0; }
	}

	public class PropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Property");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGetPropertiesFromKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPropertiesFileAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPropertiesFileSTRINGTerminalRuleCall_1_0 = (RuleCall)cPropertiesFileAssignment_1.eContents().get(0);
		
		//Property:
		//	"get properties from:" propertiesFile=STRING;
		public ParserRule getRule() { return rule; }

		//"get properties from:" propertiesFile=STRING
		public Group getGroup() { return cGroup; }

		//"get properties from:"
		public Keyword getGetPropertiesFromKeyword_0() { return cGetPropertiesFromKeyword_0; }

		//propertiesFile=STRING
		public Assignment getPropertiesFileAssignment_1() { return cPropertiesFileAssignment_1; }

		//STRING
		public RuleCall getPropertiesFileSTRINGTerminalRuleCall_1_0() { return cPropertiesFileSTRINGTerminalRuleCall_1_0; }
	}

	public class UsedDescriptionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UsedDescriptions");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDescriptionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cDescriptionAlternatives_1_0 = (Alternatives)cDescriptionAssignment_1.eContents().get(0);
		private final RuleCall cDescriptionUIDescriptionImportParserRuleCall_1_0_0 = (RuleCall)cDescriptionAlternatives_1_0.eContents().get(0);
		private final RuleCall cDescriptionComplexComponentParserRuleCall_1_0_1 = (RuleCall)cDescriptionAlternatives_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cLocalNameAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cLocalNameSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cLocalNameAssignment_2_1.eContents().get(0);
		
		//UsedDescriptions:
		//	"use: " description=(UIDescriptionImport | complexComponent) (" as: " localName=STRING)?;
		public ParserRule getRule() { return rule; }

		//"use: " description=(UIDescriptionImport | complexComponent) (" as: " localName=STRING)?
		public Group getGroup() { return cGroup; }

		//"use: "
		public Keyword getUseKeyword_0() { return cUseKeyword_0; }

		//description=(UIDescriptionImport | complexComponent)
		public Assignment getDescriptionAssignment_1() { return cDescriptionAssignment_1; }

		//UIDescriptionImport | complexComponent
		public Alternatives getDescriptionAlternatives_1_0() { return cDescriptionAlternatives_1_0; }

		//UIDescriptionImport
		public RuleCall getDescriptionUIDescriptionImportParserRuleCall_1_0_0() { return cDescriptionUIDescriptionImportParserRuleCall_1_0_0; }

		//complexComponent
		public RuleCall getDescriptionComplexComponentParserRuleCall_1_0_1() { return cDescriptionComplexComponentParserRuleCall_1_0_1; }

		//(" as: " localName=STRING)?
		public Group getGroup_2() { return cGroup_2; }

		//" as: "
		public Keyword getAsKeyword_2_0() { return cAsKeyword_2_0; }

		//localName=STRING
		public Assignment getLocalNameAssignment_2_1() { return cLocalNameAssignment_2_1; }

		//STRING
		public RuleCall getLocalNameSTRINGTerminalRuleCall_2_1_0() { return cLocalNameSTRINGTerminalRuleCall_2_1_0; }
	}

	public class AreaCountElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AreaCount");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAreaCountKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cAreaCountAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAreaCountINTTerminalRuleCall_1_0 = (RuleCall)cAreaCountAssignment_1.eContents().get(0);
		
		//AreaCount:
		//	"Area count: " areaCount=INT;
		public ParserRule getRule() { return rule; }

		//"Area count: " areaCount=INT
		public Group getGroup() { return cGroup; }

		//"Area count: "
		public Keyword getAreaCountKeyword_0() { return cAreaCountKeyword_0; }

		//areaCount=INT
		public Assignment getAreaCountAssignment_1() { return cAreaCountAssignment_1; }

		//INT
		public RuleCall getAreaCountINTTerminalRuleCall_1_0() { return cAreaCountINTTerminalRuleCall_1_0; }
	}

	public class DefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Definition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDEFKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cConcreteDefitionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cConcreteDefitionComponentDefinitionParserRuleCall_1_0 = (RuleCall)cConcreteDefitionAssignment_1.eContents().get(0);
		private final Keyword cENDDEFKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Definition:
		//	"DEF " concreteDefition=ComponentDefinition "END DEF";
		public ParserRule getRule() { return rule; }

		//"DEF " concreteDefition=ComponentDefinition "END DEF"
		public Group getGroup() { return cGroup; }

		//"DEF "
		public Keyword getDEFKeyword_0() { return cDEFKeyword_0; }

		//concreteDefition=ComponentDefinition
		public Assignment getConcreteDefitionAssignment_1() { return cConcreteDefitionAssignment_1; }

		//ComponentDefinition
		public RuleCall getConcreteDefitionComponentDefinitionParserRuleCall_1_0() { return cConcreteDefitionComponentDefinitionParserRuleCall_1_0; }

		//"END DEF"
		public Keyword getENDDEFKeyword_2() { return cENDDEFKeyword_2; }
	}

	public class TypeDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TypeDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeTypeParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		
		//TypeDefinition:
		//	"type: " type=Type;
		public ParserRule getRule() { return rule; }

		//"type: " type=Type
		public Group getGroup() { return cGroup; }

		//"type: "
		public Keyword getTypeKeyword_0() { return cTypeKeyword_0; }

		//type=Type
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }

		//Type
		public RuleCall getTypeTypeParserRuleCall_1_0() { return cTypeTypeParserRuleCall_1_0; }
	}

	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cWINDOWKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cINNERCOMPLEXKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//Type:
		//	"WINDOW" | "INNERCOMPLEX";
		public ParserRule getRule() { return rule; }

		//"WINDOW" | "INNERCOMPLEX"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"WINDOW"
		public Keyword getWINDOWKeyword_0() { return cWINDOWKeyword_0; }

		//"INNERCOMPLEX"
		public Keyword getINNERCOMPLEXKeyword_1() { return cINNERCOMPLEXKeyword_1; }
	}

	public class UIDescriptionImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UIDescriptionImport");
		private final Assignment cDescriptionNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cDescriptionNameSTRINGTerminalRuleCall_0 = (RuleCall)cDescriptionNameAssignment.eContents().get(0);
		
		//UIDescriptionImport:
		//	descriptionName=STRING;
		public ParserRule getRule() { return rule; }

		//descriptionName=STRING
		public Assignment getDescriptionNameAssignment() { return cDescriptionNameAssignment; }

		//STRING
		public RuleCall getDescriptionNameSTRINGTerminalRuleCall_0() { return cDescriptionNameSTRINGTerminalRuleCall_0; }
	}

	public class ComplexComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "complexComponent");
		private final RuleCall cMultiselectionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//complexComponent:
		//	Multiselection;
		public ParserRule getRule() { return rule; }

		//Multiselection
		public RuleCall getMultiselectionParserRuleCall() { return cMultiselectionParserRuleCall; }
	}

	public class MultiselectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Multiselection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDescriptionNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cDescriptionNameMultiselectionKeyword_0_0 = (Keyword)cDescriptionNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLessThanSignKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cInputTypeAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cInputTypeSTRINGTerminalRuleCall_1_1_0 = (RuleCall)cInputTypeAssignment_1_1.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//Multiselection:
		//	descriptionName="Multiselection" ("<" inputType=STRING ">")?;
		public ParserRule getRule() { return rule; }

		//descriptionName="Multiselection" ("<" inputType=STRING ">")?
		public Group getGroup() { return cGroup; }

		//descriptionName="Multiselection"
		public Assignment getDescriptionNameAssignment_0() { return cDescriptionNameAssignment_0; }

		//"Multiselection"
		public Keyword getDescriptionNameMultiselectionKeyword_0_0() { return cDescriptionNameMultiselectionKeyword_0_0; }

		//("<" inputType=STRING ">")?
		public Group getGroup_1() { return cGroup_1; }

		//"<"
		public Keyword getLessThanSignKeyword_1_0() { return cLessThanSignKeyword_1_0; }

		//inputType=STRING
		public Assignment getInputTypeAssignment_1_1() { return cInputTypeAssignment_1_1; }

		//STRING
		public RuleCall getInputTypeSTRINGTerminalRuleCall_1_1_0() { return cInputTypeSTRINGTerminalRuleCall_1_1_0; }

		//">"
		public Keyword getGreaterThanSignKeyword_1_2() { return cGreaterThanSignKeyword_1_2; }
	}

	public class AreaAssignmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AreaAssignment");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cAreaKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cAreaAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cAreaINTTerminalRuleCall_0_1_0 = (RuleCall)cAreaAssignment_0_1.eContents().get(0);
		private final Keyword cLessThanSignHyphenMinusKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cElementsAssignment_0_3 = (Assignment)cGroup_0.eContents().get(3);
		private final RuleCall cElementsSTRINGTerminalRuleCall_0_3_0 = (RuleCall)cElementsAssignment_0_3.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cElementsAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cElementsSTRINGTerminalRuleCall_1_0_0 = (RuleCall)cElementsAssignment_1_0.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Keyword cAreaKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Assignment cAreaAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cAreaINTTerminalRuleCall_1_3_0 = (RuleCall)cAreaAssignment_1_3.eContents().get(0);
		
		//AreaAssignment:
		//	"Area:" area=INT "<-" elements+=STRING+ | elements+=STRING+ "->" "Area:" area=INT;
		public ParserRule getRule() { return rule; }

		//"Area:" area=INT "<-" elements+=STRING+ | elements+=STRING+ "->" "Area:" area=INT
		public Alternatives getAlternatives() { return cAlternatives; }

		//"Area:" area=INT "<-" elements+=STRING+
		public Group getGroup_0() { return cGroup_0; }

		//"Area:"
		public Keyword getAreaKeyword_0_0() { return cAreaKeyword_0_0; }

		//area=INT
		public Assignment getAreaAssignment_0_1() { return cAreaAssignment_0_1; }

		//INT
		public RuleCall getAreaINTTerminalRuleCall_0_1_0() { return cAreaINTTerminalRuleCall_0_1_0; }

		//"<-"
		public Keyword getLessThanSignHyphenMinusKeyword_0_2() { return cLessThanSignHyphenMinusKeyword_0_2; }

		//elements+=STRING+
		public Assignment getElementsAssignment_0_3() { return cElementsAssignment_0_3; }

		//STRING
		public RuleCall getElementsSTRINGTerminalRuleCall_0_3_0() { return cElementsSTRINGTerminalRuleCall_0_3_0; }

		//elements+=STRING+ "->" "Area:" area=INT
		public Group getGroup_1() { return cGroup_1; }

		//elements+=STRING+
		public Assignment getElementsAssignment_1_0() { return cElementsAssignment_1_0; }

		//STRING
		public RuleCall getElementsSTRINGTerminalRuleCall_1_0_0() { return cElementsSTRINGTerminalRuleCall_1_0_0; }

		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_1_1() { return cHyphenMinusGreaterThanSignKeyword_1_1; }

		//"Area:"
		public Keyword getAreaKeyword_1_2() { return cAreaKeyword_1_2; }

		//area=INT
		public Assignment getAreaAssignment_1_3() { return cAreaAssignment_1_3; }

		//INT
		public RuleCall getAreaINTTerminalRuleCall_1_3_0() { return cAreaINTTerminalRuleCall_1_3_0; }
	}

	public class ComponentDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ComponentDefinition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLabelDefinitionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cButtonDefinitionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTextfieldDefinitionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cTreeDefinitionParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cTableDefinitionParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cRadioboxDefinitionParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cCheckboxDefinitionParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//ComponentDefinition:
		//	LabelDefinition | ButtonDefinition | TextfieldDefinition | TreeDefinition | TableDefinition | RadioboxDefinition |
		//	CheckboxDefinition;
		public ParserRule getRule() { return rule; }

		//LabelDefinition | ButtonDefinition | TextfieldDefinition | TreeDefinition | TableDefinition | RadioboxDefinition |
		//CheckboxDefinition
		public Alternatives getAlternatives() { return cAlternatives; }

		//LabelDefinition
		public RuleCall getLabelDefinitionParserRuleCall_0() { return cLabelDefinitionParserRuleCall_0; }

		//ButtonDefinition
		public RuleCall getButtonDefinitionParserRuleCall_1() { return cButtonDefinitionParserRuleCall_1; }

		//TextfieldDefinition
		public RuleCall getTextfieldDefinitionParserRuleCall_2() { return cTextfieldDefinitionParserRuleCall_2; }

		//TreeDefinition
		public RuleCall getTreeDefinitionParserRuleCall_3() { return cTreeDefinitionParserRuleCall_3; }

		//TableDefinition
		public RuleCall getTableDefinitionParserRuleCall_4() { return cTableDefinitionParserRuleCall_4; }

		//RadioboxDefinition
		public RuleCall getRadioboxDefinitionParserRuleCall_5() { return cRadioboxDefinitionParserRuleCall_5; }

		//CheckboxDefinition
		public RuleCall getCheckboxDefinitionParserRuleCall_6() { return cCheckboxDefinitionParserRuleCall_6; }
	}

	public class CheckboxDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CheckboxDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cTypeCheckboxKeyword_0_0 = (Keyword)cTypeAssignment_0.eContents().get(0);
		private final Keyword cAsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTextKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTextAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cTextAssignment_4_1.eContents().get(0);
		
		//CheckboxDefinition:
		//	type="Checkbox" " as " name=STRING ":" ("text=" text=STRING)?;
		public ParserRule getRule() { return rule; }

		//type="Checkbox" " as " name=STRING ":" ("text=" text=STRING)?
		public Group getGroup() { return cGroup; }

		//type="Checkbox"
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }

		//"Checkbox"
		public Keyword getTypeCheckboxKeyword_0_0() { return cTypeCheckboxKeyword_0_0; }

		//" as "
		public Keyword getAsKeyword_1() { return cAsKeyword_1; }

		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//("text=" text=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"text="
		public Keyword getTextKeyword_4_0() { return cTextKeyword_4_0; }

		//text=STRING
		public Assignment getTextAssignment_4_1() { return cTextAssignment_4_1; }

		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_4_1_0() { return cTextSTRINGTerminalRuleCall_4_1_0; }
	}

	public class RadioboxDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RadioboxDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cTypeRadioboxKeyword_0_0 = (Keyword)cTypeAssignment_0.eContents().get(0);
		private final Keyword cAsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTextKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTextAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cTextAssignment_4_1.eContents().get(0);
		
		//RadioboxDefinition:
		//	type="Radiobox" " as " name=STRING ":" ("text=" text=STRING)?;
		public ParserRule getRule() { return rule; }

		//type="Radiobox" " as " name=STRING ":" ("text=" text=STRING)?
		public Group getGroup() { return cGroup; }

		//type="Radiobox"
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }

		//"Radiobox"
		public Keyword getTypeRadioboxKeyword_0_0() { return cTypeRadioboxKeyword_0_0; }

		//" as "
		public Keyword getAsKeyword_1() { return cAsKeyword_1; }

		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//("text=" text=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"text="
		public Keyword getTextKeyword_4_0() { return cTextKeyword_4_0; }

		//text=STRING
		public Assignment getTextAssignment_4_1() { return cTextAssignment_4_1; }

		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_4_1_0() { return cTextSTRINGTerminalRuleCall_4_1_0; }
	}

	public class TableDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TableDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cTypeTableKeyword_0_0 = (Keyword)cTypeAssignment_0.eContents().get(0);
		private final Keyword cAsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTextKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTextAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cTextAssignment_4_1.eContents().get(0);
		
		//TableDefinition:
		//	type="Table" " as " name=STRING ":" ("text=" text=STRING)?;
		public ParserRule getRule() { return rule; }

		//type="Table" " as " name=STRING ":" ("text=" text=STRING)?
		public Group getGroup() { return cGroup; }

		//type="Table"
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }

		//"Table"
		public Keyword getTypeTableKeyword_0_0() { return cTypeTableKeyword_0_0; }

		//" as "
		public Keyword getAsKeyword_1() { return cAsKeyword_1; }

		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//("text=" text=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"text="
		public Keyword getTextKeyword_4_0() { return cTextKeyword_4_0; }

		//text=STRING
		public Assignment getTextAssignment_4_1() { return cTextAssignment_4_1; }

		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_4_1_0() { return cTextSTRINGTerminalRuleCall_4_1_0; }
	}

	public class TreeDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TreeDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cTypeTreeKeyword_0_0 = (Keyword)cTypeAssignment_0.eContents().get(0);
		private final Keyword cAsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTextKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTextAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cTextAssignment_4_1.eContents().get(0);
		
		//TreeDefinition:
		//	type="Tree" " as " name=STRING ":" ("text=" text=STRING)?;
		public ParserRule getRule() { return rule; }

		//type="Tree" " as " name=STRING ":" ("text=" text=STRING)?
		public Group getGroup() { return cGroup; }

		//type="Tree"
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }

		//"Tree"
		public Keyword getTypeTreeKeyword_0_0() { return cTypeTreeKeyword_0_0; }

		//" as "
		public Keyword getAsKeyword_1() { return cAsKeyword_1; }

		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//("text=" text=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"text="
		public Keyword getTextKeyword_4_0() { return cTextKeyword_4_0; }

		//text=STRING
		public Assignment getTextAssignment_4_1() { return cTextAssignment_4_1; }

		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_4_1_0() { return cTextSTRINGTerminalRuleCall_4_1_0; }
	}

	public class TextfieldDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TextfieldDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cTypeTextfieldKeyword_0_0 = (Keyword)cTypeAssignment_0.eContents().get(0);
		private final Keyword cAsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTextKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTextAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cTextAssignment_4_1.eContents().get(0);
		
		//TextfieldDefinition:
		//	type="Textfield" " as " name=STRING ":" ("text=" text=STRING)?;
		public ParserRule getRule() { return rule; }

		//type="Textfield" " as " name=STRING ":" ("text=" text=STRING)?
		public Group getGroup() { return cGroup; }

		//type="Textfield"
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }

		//"Textfield"
		public Keyword getTypeTextfieldKeyword_0_0() { return cTypeTextfieldKeyword_0_0; }

		//" as "
		public Keyword getAsKeyword_1() { return cAsKeyword_1; }

		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//("text=" text=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"text="
		public Keyword getTextKeyword_4_0() { return cTextKeyword_4_0; }

		//text=STRING
		public Assignment getTextAssignment_4_1() { return cTextAssignment_4_1; }

		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_4_1_0() { return cTextSTRINGTerminalRuleCall_4_1_0; }
	}

	public class ButtonDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ButtonDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cTypeButtonKeyword_0_0 = (Keyword)cTypeAssignment_0.eContents().get(0);
		private final Keyword cAsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPropertyKeyKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPropertyKeyAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPropertyKeySTRINGTerminalRuleCall_4_1_0 = (RuleCall)cPropertyKeyAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTextKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTextAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cTextAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cInteractiontypeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cInteractiontypeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cInteractiontypeInteractiontypeParserRuleCall_6_1_0 = (RuleCall)cInteractiontypeAssignment_6_1.eContents().get(0);
		
		//ButtonDefinition:
		//	type="Button" " as " name=STRING ":" ("propertyKey=" propertyKey=STRING)? ("text=" text=STRING)? ("interactiontype="
		//	interactiontype+=Interactiontype+)?;
		public ParserRule getRule() { return rule; }

		//type="Button" " as " name=STRING ":" ("propertyKey=" propertyKey=STRING)? ("text=" text=STRING)? ("interactiontype="
		//interactiontype+=Interactiontype+)?
		public Group getGroup() { return cGroup; }

		//type="Button"
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }

		//"Button"
		public Keyword getTypeButtonKeyword_0_0() { return cTypeButtonKeyword_0_0; }

		//" as "
		public Keyword getAsKeyword_1() { return cAsKeyword_1; }

		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//("propertyKey=" propertyKey=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"propertyKey="
		public Keyword getPropertyKeyKeyword_4_0() { return cPropertyKeyKeyword_4_0; }

		//propertyKey=STRING
		public Assignment getPropertyKeyAssignment_4_1() { return cPropertyKeyAssignment_4_1; }

		//STRING
		public RuleCall getPropertyKeySTRINGTerminalRuleCall_4_1_0() { return cPropertyKeySTRINGTerminalRuleCall_4_1_0; }

		//("text=" text=STRING)?
		public Group getGroup_5() { return cGroup_5; }

		//"text="
		public Keyword getTextKeyword_5_0() { return cTextKeyword_5_0; }

		//text=STRING
		public Assignment getTextAssignment_5_1() { return cTextAssignment_5_1; }

		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_5_1_0() { return cTextSTRINGTerminalRuleCall_5_1_0; }

		//("interactiontype=" interactiontype+=Interactiontype+)?
		public Group getGroup_6() { return cGroup_6; }

		//"interactiontype="
		public Keyword getInteractiontypeKeyword_6_0() { return cInteractiontypeKeyword_6_0; }

		//interactiontype+=Interactiontype+
		public Assignment getInteractiontypeAssignment_6_1() { return cInteractiontypeAssignment_6_1; }

		//Interactiontype
		public RuleCall getInteractiontypeInteractiontypeParserRuleCall_6_1_0() { return cInteractiontypeInteractiontypeParserRuleCall_6_1_0; }
	}

	public class InteractionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Interaction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameSTRINGTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cInteractiontypeParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//Interaction:
		//	name=STRING " type=" Interactiontype;
		public ParserRule getRule() { return rule; }

		//name=STRING " type=" Interactiontype
		public Group getGroup() { return cGroup; }

		//name=STRING
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_0_0() { return cNameSTRINGTerminalRuleCall_0_0; }

		//" type="
		public Keyword getTypeKeyword_1() { return cTypeKeyword_1; }

		//Interactiontype
		public RuleCall getInteractiontypeParserRuleCall_2() { return cInteractiontypeParserRuleCall_2; }
	}

	public class LabelDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "LabelDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cTypeLabelKeyword_0_0 = (Keyword)cTypeAssignment_0.eContents().get(0);
		private final Keyword cAsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPropertyKeyKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPropertyKeyAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPropertyKeySTRINGTerminalRuleCall_4_1_0 = (RuleCall)cPropertyKeyAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTextKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTextAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cTextAssignment_5_1.eContents().get(0);
		
		//LabelDefinition:
		//	type="Label" " as " name=STRING ":" ("propertyKey=" propertyKey=STRING)? ("text=" text=STRING)?;
		public ParserRule getRule() { return rule; }

		//type="Label" " as " name=STRING ":" ("propertyKey=" propertyKey=STRING)? ("text=" text=STRING)?
		public Group getGroup() { return cGroup; }

		//type="Label"
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }

		//"Label"
		public Keyword getTypeLabelKeyword_0_0() { return cTypeLabelKeyword_0_0; }

		//" as "
		public Keyword getAsKeyword_1() { return cAsKeyword_1; }

		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//("propertyKey=" propertyKey=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"propertyKey="
		public Keyword getPropertyKeyKeyword_4_0() { return cPropertyKeyKeyword_4_0; }

		//propertyKey=STRING
		public Assignment getPropertyKeyAssignment_4_1() { return cPropertyKeyAssignment_4_1; }

		//STRING
		public RuleCall getPropertyKeySTRINGTerminalRuleCall_4_1_0() { return cPropertyKeySTRINGTerminalRuleCall_4_1_0; }

		//("text=" text=STRING)?
		public Group getGroup_5() { return cGroup_5; }

		//"text="
		public Keyword getTextKeyword_5_0() { return cTextKeyword_5_0; }

		//text=STRING
		public Assignment getTextAssignment_5_1() { return cTextAssignment_5_1; }

		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_5_1_0() { return cTextSTRINGTerminalRuleCall_5_1_0; }
	}

	public class InteractiontypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Interactiontype");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cClickKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cChangeTextKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//Interactiontype:
		//	"Click" | "ChangeText";
		public ParserRule getRule() { return rule; }

		//"Click" | "ChangeText"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"Click"
		public Keyword getClickKeyword_0() { return cClickKeyword_0; }

		//"ChangeText"
		public Keyword getChangeTextKeyword_1() { return cChangeTextKeyword_1; }
	}
	
	
	private final UIDescriptionElements pUIDescription;
	private final PropertyElements pProperty;
	private final UsedDescriptionsElements pUsedDescriptions;
	private final AreaCountElements pAreaCount;
	private final DefinitionElements pDefinition;
	private final TypeDefinitionElements pTypeDefinition;
	private final TypeElements pType;
	private final UIDescriptionImportElements pUIDescriptionImport;
	private final ComplexComponentElements pComplexComponent;
	private final MultiselectionElements pMultiselection;
	private final AreaAssignmentElements pAreaAssignment;
	private final ComponentDefinitionElements pComponentDefinition;
	private final CheckboxDefinitionElements pCheckboxDefinition;
	private final RadioboxDefinitionElements pRadioboxDefinition;
	private final TableDefinitionElements pTableDefinition;
	private final TreeDefinitionElements pTreeDefinition;
	private final TextfieldDefinitionElements pTextfieldDefinition;
	private final ButtonDefinitionElements pButtonDefinition;
	private final InteractionElements pInteraction;
	private final LabelDefinitionElements pLabelDefinition;
	private final InteractiontypeElements pInteractiontype;
	private final TerminalRule tWS;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GuiDSLGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pUIDescription = new UIDescriptionElements();
		this.pProperty = new PropertyElements();
		this.pUsedDescriptions = new UsedDescriptionsElements();
		this.pAreaCount = new AreaCountElements();
		this.pDefinition = new DefinitionElements();
		this.pTypeDefinition = new TypeDefinitionElements();
		this.pType = new TypeElements();
		this.pUIDescriptionImport = new UIDescriptionImportElements();
		this.pComplexComponent = new ComplexComponentElements();
		this.pMultiselection = new MultiselectionElements();
		this.pAreaAssignment = new AreaAssignmentElements();
		this.pComponentDefinition = new ComponentDefinitionElements();
		this.pCheckboxDefinition = new CheckboxDefinitionElements();
		this.pRadioboxDefinition = new RadioboxDefinitionElements();
		this.pTableDefinition = new TableDefinitionElements();
		this.pTreeDefinition = new TreeDefinitionElements();
		this.pTextfieldDefinition = new TextfieldDefinitionElements();
		this.pButtonDefinition = new ButtonDefinitionElements();
		this.pInteraction = new InteractionElements();
		this.pLabelDefinition = new LabelDefinitionElements();
		this.pInteractiontype = new InteractiontypeElements();
		this.tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "WS");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.deg.xtext.gui.GuiDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//UIDescription:
	//	areaCount=AreaCount typeDefinition=TypeDefinition & property=Property usedDescriptions+=UsedDescriptions*
	//	definitions+=Definition* areas+=AreaAssignment*;
	public UIDescriptionElements getUIDescriptionAccess() {
		return pUIDescription;
	}
	
	public ParserRule getUIDescriptionRule() {
		return getUIDescriptionAccess().getRule();
	}

	//Property:
	//	"get properties from:" propertiesFile=STRING;
	public PropertyElements getPropertyAccess() {
		return pProperty;
	}
	
	public ParserRule getPropertyRule() {
		return getPropertyAccess().getRule();
	}

	//UsedDescriptions:
	//	"use: " description=(UIDescriptionImport | complexComponent) (" as: " localName=STRING)?;
	public UsedDescriptionsElements getUsedDescriptionsAccess() {
		return pUsedDescriptions;
	}
	
	public ParserRule getUsedDescriptionsRule() {
		return getUsedDescriptionsAccess().getRule();
	}

	//AreaCount:
	//	"Area count: " areaCount=INT;
	public AreaCountElements getAreaCountAccess() {
		return pAreaCount;
	}
	
	public ParserRule getAreaCountRule() {
		return getAreaCountAccess().getRule();
	}

	//Definition:
	//	"DEF " concreteDefition=ComponentDefinition "END DEF";
	public DefinitionElements getDefinitionAccess() {
		return pDefinition;
	}
	
	public ParserRule getDefinitionRule() {
		return getDefinitionAccess().getRule();
	}

	//TypeDefinition:
	//	"type: " type=Type;
	public TypeDefinitionElements getTypeDefinitionAccess() {
		return pTypeDefinition;
	}
	
	public ParserRule getTypeDefinitionRule() {
		return getTypeDefinitionAccess().getRule();
	}

	//Type:
	//	"WINDOW" | "INNERCOMPLEX";
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}

	//UIDescriptionImport:
	//	descriptionName=STRING;
	public UIDescriptionImportElements getUIDescriptionImportAccess() {
		return pUIDescriptionImport;
	}
	
	public ParserRule getUIDescriptionImportRule() {
		return getUIDescriptionImportAccess().getRule();
	}

	//complexComponent:
	//	Multiselection;
	public ComplexComponentElements getComplexComponentAccess() {
		return pComplexComponent;
	}
	
	public ParserRule getComplexComponentRule() {
		return getComplexComponentAccess().getRule();
	}

	//Multiselection:
	//	descriptionName="Multiselection" ("<" inputType=STRING ">")?;
	public MultiselectionElements getMultiselectionAccess() {
		return pMultiselection;
	}
	
	public ParserRule getMultiselectionRule() {
		return getMultiselectionAccess().getRule();
	}

	//AreaAssignment:
	//	"Area:" area=INT "<-" elements+=STRING+ | elements+=STRING+ "->" "Area:" area=INT;
	public AreaAssignmentElements getAreaAssignmentAccess() {
		return pAreaAssignment;
	}
	
	public ParserRule getAreaAssignmentRule() {
		return getAreaAssignmentAccess().getRule();
	}

	//ComponentDefinition:
	//	LabelDefinition | ButtonDefinition | TextfieldDefinition | TreeDefinition | TableDefinition | RadioboxDefinition |
	//	CheckboxDefinition;
	public ComponentDefinitionElements getComponentDefinitionAccess() {
		return pComponentDefinition;
	}
	
	public ParserRule getComponentDefinitionRule() {
		return getComponentDefinitionAccess().getRule();
	}

	//CheckboxDefinition:
	//	type="Checkbox" " as " name=STRING ":" ("text=" text=STRING)?;
	public CheckboxDefinitionElements getCheckboxDefinitionAccess() {
		return pCheckboxDefinition;
	}
	
	public ParserRule getCheckboxDefinitionRule() {
		return getCheckboxDefinitionAccess().getRule();
	}

	//RadioboxDefinition:
	//	type="Radiobox" " as " name=STRING ":" ("text=" text=STRING)?;
	public RadioboxDefinitionElements getRadioboxDefinitionAccess() {
		return pRadioboxDefinition;
	}
	
	public ParserRule getRadioboxDefinitionRule() {
		return getRadioboxDefinitionAccess().getRule();
	}

	//TableDefinition:
	//	type="Table" " as " name=STRING ":" ("text=" text=STRING)?;
	public TableDefinitionElements getTableDefinitionAccess() {
		return pTableDefinition;
	}
	
	public ParserRule getTableDefinitionRule() {
		return getTableDefinitionAccess().getRule();
	}

	//TreeDefinition:
	//	type="Tree" " as " name=STRING ":" ("text=" text=STRING)?;
	public TreeDefinitionElements getTreeDefinitionAccess() {
		return pTreeDefinition;
	}
	
	public ParserRule getTreeDefinitionRule() {
		return getTreeDefinitionAccess().getRule();
	}

	//TextfieldDefinition:
	//	type="Textfield" " as " name=STRING ":" ("text=" text=STRING)?;
	public TextfieldDefinitionElements getTextfieldDefinitionAccess() {
		return pTextfieldDefinition;
	}
	
	public ParserRule getTextfieldDefinitionRule() {
		return getTextfieldDefinitionAccess().getRule();
	}

	//ButtonDefinition:
	//	type="Button" " as " name=STRING ":" ("propertyKey=" propertyKey=STRING)? ("text=" text=STRING)? ("interactiontype="
	//	interactiontype+=Interactiontype+)?;
	public ButtonDefinitionElements getButtonDefinitionAccess() {
		return pButtonDefinition;
	}
	
	public ParserRule getButtonDefinitionRule() {
		return getButtonDefinitionAccess().getRule();
	}

	//Interaction:
	//	name=STRING " type=" Interactiontype;
	public InteractionElements getInteractionAccess() {
		return pInteraction;
	}
	
	public ParserRule getInteractionRule() {
		return getInteractionAccess().getRule();
	}

	//LabelDefinition:
	//	type="Label" " as " name=STRING ":" ("propertyKey=" propertyKey=STRING)? ("text=" text=STRING)?;
	public LabelDefinitionElements getLabelDefinitionAccess() {
		return pLabelDefinition;
	}
	
	public ParserRule getLabelDefinitionRule() {
		return getLabelDefinitionAccess().getRule();
	}

	//Interactiontype:
	//	"Click" | "ChangeText";
	public InteractiontypeElements getInteractiontypeAccess() {
		return pInteractiontype;
	}
	
	public ParserRule getInteractiontypeRule() {
		return getInteractiontypeAccess().getRule();
	}

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n" | ",")+;
	public TerminalRule getWSRule() {
		return tWS;
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
