/*
* generated by Xtext
*/
package org.deg.xtext.gui.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.deg.xtext.gui.services.GuiDSLGrammarAccess;

public class GuiDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GuiDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.deg.xtext.gui.parser.antlr.internal.InternalGuiDSLParser createParser(XtextTokenStream stream) {
		return new org.deg.xtext.gui.parser.antlr.internal.InternalGuiDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "UIDescription";
	}
	
	public GuiDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GuiDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
