/*
 * generated by Xtext
 */
package org.deg.xtext.gui.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractGuiDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.deg.xtext.gui.guiDSL.GuiDSLPackage.eINSTANCE);
		return result;
	}
}
