/*
* generated by Xtext
*/
package org.deg.xtext.gui;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GuiDSLStandaloneSetup extends GuiDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new GuiDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

