/*
* generated by Xtext
*/
package org.deg.xtext.gui.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.deg.xtext.gui.services.GuiDSLGrammarAccess;

public class GuiDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private GuiDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.deg.xtext.gui.ui.contentassist.antlr.internal.InternalGuiDSLParser createParser() {
		org.deg.xtext.gui.ui.contentassist.antlr.internal.InternalGuiDSLParser result = new org.deg.xtext.gui.ui.contentassist.antlr.internal.InternalGuiDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getComponentRefinementAccess().getAlternatives(), "rule__ComponentRefinement__Alternatives");
					put(grammarAccess.getUsedDescriptionsAccess().getDescriptionAlternatives_1_0(), "rule__UsedDescriptions__DescriptionAlternatives_1_0");
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getAreaAssignmentAccess().getAlternatives(), "rule__AreaAssignment__Alternatives");
					put(grammarAccess.getComponentDefinitionAccess().getAlternatives(), "rule__ComponentDefinition__Alternatives");
					put(grammarAccess.getInteractiontypeAccess().getAlternatives(), "rule__Interactiontype__Alternatives");
					put(grammarAccess.getUIDescriptionAccess().getGroup(), "rule__UIDescription__Group__0");
					put(grammarAccess.getRefinementAccess().getGroup(), "rule__Refinement__Group__0");
					put(grammarAccess.getButtonRefinementAccess().getGroup(), "rule__ButtonRefinement__Group__0");
					put(grammarAccess.getLabelRefinementAccess().getGroup(), "rule__LabelRefinement__Group__0");
					put(grammarAccess.getPropertyAccess().getGroup(), "rule__Property__Group__0");
					put(grammarAccess.getUsedDescriptionsAccess().getGroup(), "rule__UsedDescriptions__Group__0");
					put(grammarAccess.getUsedDescriptionsAccess().getGroup_2(), "rule__UsedDescriptions__Group_2__0");
					put(grammarAccess.getAreaCountAccess().getGroup(), "rule__AreaCount__Group__0");
					put(grammarAccess.getDefinitionAccess().getGroup(), "rule__Definition__Group__0");
					put(grammarAccess.getTypeDefinitionAccess().getGroup(), "rule__TypeDefinition__Group__0");
					put(grammarAccess.getMultiselectionAccess().getGroup(), "rule__Multiselection__Group__0");
					put(grammarAccess.getMultiselectionAccess().getGroup_1(), "rule__Multiselection__Group_1__0");
					put(grammarAccess.getAreaAssignmentAccess().getGroup_0(), "rule__AreaAssignment__Group_0__0");
					put(grammarAccess.getAreaAssignmentAccess().getGroup_1(), "rule__AreaAssignment__Group_1__0");
					put(grammarAccess.getCheckboxDefinitionAccess().getGroup(), "rule__CheckboxDefinition__Group__0");
					put(grammarAccess.getCheckboxDefinitionAccess().getGroup_4(), "rule__CheckboxDefinition__Group_4__0");
					put(grammarAccess.getRadioboxDefinitionAccess().getGroup(), "rule__RadioboxDefinition__Group__0");
					put(grammarAccess.getRadioboxDefinitionAccess().getGroup_4(), "rule__RadioboxDefinition__Group_4__0");
					put(grammarAccess.getTableDefinitionAccess().getGroup(), "rule__TableDefinition__Group__0");
					put(grammarAccess.getTableDefinitionAccess().getGroup_4(), "rule__TableDefinition__Group_4__0");
					put(grammarAccess.getTreeDefinitionAccess().getGroup(), "rule__TreeDefinition__Group__0");
					put(grammarAccess.getTreeDefinitionAccess().getGroup_4(), "rule__TreeDefinition__Group_4__0");
					put(grammarAccess.getTextfieldDefinitionAccess().getGroup(), "rule__TextfieldDefinition__Group__0");
					put(grammarAccess.getTextfieldDefinitionAccess().getGroup_4(), "rule__TextfieldDefinition__Group_4__0");
					put(grammarAccess.getButtonDefinitionAccess().getGroup(), "rule__ButtonDefinition__Group__0");
					put(grammarAccess.getPropertiesAccess().getGroup(), "rule__Properties__Group__0");
					put(grammarAccess.getPropertiesAccess().getGroup_1(), "rule__Properties__Group_1__0");
					put(grammarAccess.getPropertiesAccess().getGroup_2(), "rule__Properties__Group_2__0");
					put(grammarAccess.getPropertiesAccess().getGroup_3(), "rule__Properties__Group_3__0");
					put(grammarAccess.getLabelDefinitionAccess().getGroup(), "rule__LabelDefinition__Group__0");
					put(grammarAccess.getUIDescriptionAccess().getAreaCountAssignment_0(), "rule__UIDescription__AreaCountAssignment_0");
					put(grammarAccess.getUIDescriptionAccess().getTypeDefinitionAssignment_1(), "rule__UIDescription__TypeDefinitionAssignment_1");
					put(grammarAccess.getUIDescriptionAccess().getPropertyAssignment_2(), "rule__UIDescription__PropertyAssignment_2");
					put(grammarAccess.getUIDescriptionAccess().getUsedDescriptionsAssignment_3(), "rule__UIDescription__UsedDescriptionsAssignment_3");
					put(grammarAccess.getUIDescriptionAccess().getRefinementsAssignment_4(), "rule__UIDescription__RefinementsAssignment_4");
					put(grammarAccess.getUIDescriptionAccess().getDefinitionsAssignment_5(), "rule__UIDescription__DefinitionsAssignment_5");
					put(grammarAccess.getUIDescriptionAccess().getAreasAssignment_6(), "rule__UIDescription__AreasAssignment_6");
					put(grammarAccess.getRefinementAccess().getConcreteRefinementAssignment_1(), "rule__Refinement__ConcreteRefinementAssignment_1");
					put(grammarAccess.getButtonRefinementAccess().getTypeAssignment_0(), "rule__ButtonRefinement__TypeAssignment_0");
					put(grammarAccess.getButtonRefinementAccess().getNameAssignment_2(), "rule__ButtonRefinement__NameAssignment_2");
					put(grammarAccess.getButtonRefinementAccess().getPropertiesAssignment_3(), "rule__ButtonRefinement__PropertiesAssignment_3");
					put(grammarAccess.getLabelRefinementAccess().getTypeAssignment_0(), "rule__LabelRefinement__TypeAssignment_0");
					put(grammarAccess.getLabelRefinementAccess().getNameAssignment_2(), "rule__LabelRefinement__NameAssignment_2");
					put(grammarAccess.getLabelRefinementAccess().getPropertiesAssignment_3(), "rule__LabelRefinement__PropertiesAssignment_3");
					put(grammarAccess.getPropertyAccess().getPropertiesFileAssignment_1(), "rule__Property__PropertiesFileAssignment_1");
					put(grammarAccess.getUsedDescriptionsAccess().getDescriptionAssignment_1(), "rule__UsedDescriptions__DescriptionAssignment_1");
					put(grammarAccess.getUsedDescriptionsAccess().getLocalNameAssignment_2_1(), "rule__UsedDescriptions__LocalNameAssignment_2_1");
					put(grammarAccess.getAreaCountAccess().getAreaCountAssignment_1(), "rule__AreaCount__AreaCountAssignment_1");
					put(grammarAccess.getDefinitionAccess().getConcreteDefitionAssignment_1(), "rule__Definition__ConcreteDefitionAssignment_1");
					put(grammarAccess.getTypeDefinitionAccess().getTypeAssignment_1(), "rule__TypeDefinition__TypeAssignment_1");
					put(grammarAccess.getUIDescriptionImportAccess().getDescriptionNameAssignment(), "rule__UIDescriptionImport__DescriptionNameAssignment");
					put(grammarAccess.getMultiselectionAccess().getDescriptionNameAssignment_0(), "rule__Multiselection__DescriptionNameAssignment_0");
					put(grammarAccess.getMultiselectionAccess().getInputTypeAssignment_1_1(), "rule__Multiselection__InputTypeAssignment_1_1");
					put(grammarAccess.getAreaAssignmentAccess().getAreaAssignment_0_1(), "rule__AreaAssignment__AreaAssignment_0_1");
					put(grammarAccess.getAreaAssignmentAccess().getElementsAssignment_0_3(), "rule__AreaAssignment__ElementsAssignment_0_3");
					put(grammarAccess.getAreaAssignmentAccess().getElementsAssignment_1_0(), "rule__AreaAssignment__ElementsAssignment_1_0");
					put(grammarAccess.getAreaAssignmentAccess().getAreaAssignment_1_3(), "rule__AreaAssignment__AreaAssignment_1_3");
					put(grammarAccess.getCheckboxDefinitionAccess().getTypeAssignment_0(), "rule__CheckboxDefinition__TypeAssignment_0");
					put(grammarAccess.getCheckboxDefinitionAccess().getNameAssignment_2(), "rule__CheckboxDefinition__NameAssignment_2");
					put(grammarAccess.getCheckboxDefinitionAccess().getTextAssignment_4_1(), "rule__CheckboxDefinition__TextAssignment_4_1");
					put(grammarAccess.getRadioboxDefinitionAccess().getTypeAssignment_0(), "rule__RadioboxDefinition__TypeAssignment_0");
					put(grammarAccess.getRadioboxDefinitionAccess().getNameAssignment_2(), "rule__RadioboxDefinition__NameAssignment_2");
					put(grammarAccess.getRadioboxDefinitionAccess().getTextAssignment_4_1(), "rule__RadioboxDefinition__TextAssignment_4_1");
					put(grammarAccess.getTableDefinitionAccess().getTypeAssignment_0(), "rule__TableDefinition__TypeAssignment_0");
					put(grammarAccess.getTableDefinitionAccess().getNameAssignment_2(), "rule__TableDefinition__NameAssignment_2");
					put(grammarAccess.getTableDefinitionAccess().getTextAssignment_4_1(), "rule__TableDefinition__TextAssignment_4_1");
					put(grammarAccess.getTreeDefinitionAccess().getTypeAssignment_0(), "rule__TreeDefinition__TypeAssignment_0");
					put(grammarAccess.getTreeDefinitionAccess().getNameAssignment_2(), "rule__TreeDefinition__NameAssignment_2");
					put(grammarAccess.getTreeDefinitionAccess().getTextAssignment_4_1(), "rule__TreeDefinition__TextAssignment_4_1");
					put(grammarAccess.getTextfieldDefinitionAccess().getTypeAssignment_0(), "rule__TextfieldDefinition__TypeAssignment_0");
					put(grammarAccess.getTextfieldDefinitionAccess().getNameAssignment_2(), "rule__TextfieldDefinition__NameAssignment_2");
					put(grammarAccess.getTextfieldDefinitionAccess().getTextAssignment_4_1(), "rule__TextfieldDefinition__TextAssignment_4_1");
					put(grammarAccess.getButtonDefinitionAccess().getTypeAssignment_0(), "rule__ButtonDefinition__TypeAssignment_0");
					put(grammarAccess.getButtonDefinitionAccess().getNameAssignment_2(), "rule__ButtonDefinition__NameAssignment_2");
					put(grammarAccess.getButtonDefinitionAccess().getPropertiesAssignment_3(), "rule__ButtonDefinition__PropertiesAssignment_3");
					put(grammarAccess.getPropertiesAccess().getPropertyKeyAssignment_1_1(), "rule__Properties__PropertyKeyAssignment_1_1");
					put(grammarAccess.getPropertiesAccess().getTextAssignment_2_1(), "rule__Properties__TextAssignment_2_1");
					put(grammarAccess.getPropertiesAccess().getInteractiontypeAssignment_3_1(), "rule__Properties__InteractiontypeAssignment_3_1");
					put(grammarAccess.getLabelDefinitionAccess().getTypeAssignment_0(), "rule__LabelDefinition__TypeAssignment_0");
					put(grammarAccess.getLabelDefinitionAccess().getNameAssignment_2(), "rule__LabelDefinition__NameAssignment_2");
					put(grammarAccess.getLabelDefinitionAccess().getPropertiesAssignment_3(), "rule__LabelDefinition__PropertiesAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.deg.xtext.gui.ui.contentassist.antlr.internal.InternalGuiDSLParser typedParser = (org.deg.xtext.gui.ui.contentassist.antlr.internal.InternalGuiDSLParser) parser;
			typedParser.entryRuleUIDescription();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public GuiDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GuiDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
